Repository PacificBiosciences/pb-human-wgs-workflow-snakemake, pull requests merged in 2021-12, with the labels that each got.

#38 changed glnexus container url and version
  config.yaml
  rules/cohort_glnexus.smk
Labels: enhancement

#40 Added tutorial
  README.md
  Tutorial.md
Labels: documentation

#41 Update pbsv from v2.6.0 to v2.8
  rules/cohort_pbsv.smk
  rules/envs/pbsv.yaml
  rules/sample_pbsv.smk
Labels: version_bump

#34 Absolute tg count
  Tutorial.md
  process_sample.smk
  rules/sample_tandem_genotypes.smk
Labels: enhancement

#42 Version bumps, tutorial, absolute tandem repeat counts
  README.md
  Tutorial.md
  config.yaml
  process_sample.smk
  rules/cohort_glnexus.smk
  rules/cohort_pbsv.smk
  rules/cohort_slivar.smk
  rules/envs/pbsv.yaml
  rules/sample_pbsv.smk
  rules/sample_tandem_genotypes.smk
Labels: documentation, enhancement, version_bump

#43 pileup width changed for DeepVariant v1.3.0
  rules/sample_deepvariant.smk
Labels: bug

#45 moved many tasks to localrules
  process_sample.smk
  process_smrtcells.sh
  process_smrtcells.smk
  rules/cohort_common.smk
  rules/cohort_glnexus.smk
  rules/cohort_hifiasm.smk
  rules/cohort_pbsv.smk
  rules/cohort_slivar.smk
  rules/cohort_svpack.smk
  rules/sample_deepvariant.smk
  rules/sample_gc_coverage.smk
  rules/sample_hifiasm.smk
  rules/sample_tandem_genotypes.smk
  rules/smrtcell_stats.smk
Labels: enhancement
