Repository PacificBiosciences/pb-human-wgs-workflow-snakemake, pull requests merged in 2022-06, with the labels that each got.

#91 Feature/single pass deepvariant
  config.yaml
  rules/sample_deepvariant.smk
  rules/sample_whatshap.smk
Labels: enhancement, version_bump

#94 pbmm2 version bump
  rules/envs/pbmm2.yaml
Labels: version_bump

#96 update tutorial FAQ with CHM13
  Tutorial.md
  example_cohort.yaml
  rules/cohort_slivar.smk
Labels: documentation

#97 update snakemake profiles
  profiles/lsf/config.yaml
  profiles/sge/config.yaml
  profiles/slurm/config.yaml
Labels: enhancement

#92 move deepvariant HPC configuration to variables.env
  config.yaml
  process_sample.local.sh
  rules/sample_deepvariant.smk
  variables.env
Labels: enhancement

#98 remove message directives from each rule
  rules/cohort_common.smk
  rules/cohort_glnexus.smk
  rules/cohort_hifiasm.smk
  rules/cohort_pbsv.smk
  rules/cohort_slivar.smk
  rules/cohort_svpack.smk
  rules/sample_common.smk
  rules/sample_deepvariant.smk
  rules/sample_gc_coverage.smk
  rules/sample_hifiasm.smk
  rules/sample_jellyfish.smk
  rules/sample_kmer_consistency.smk
  rules/sample_mosdepth.smk
  rules/sample_pbsv.smk
  rules/sample_tandem_genotypes.smk
  rules/sample_whatshap.smk
  rules/smrtcell_coverage_qc.smk
  rules/smrtcell_jellyfish.smk
  rules/smrtcell_mosdepth.smk
  rules/smrtcell_pbmm2.smk
  rules/smrtcell_stats.smk
Labels: enhancement
