Repository PacificBiosciences/pb-human-wgs-workflow-snakemake, pull requests merged in 2022-02, with the labels that each got.

#68 Trio assembly updates
  process_cohort.cluster.yaml
  process_cohort.smk
  rules/cohort_hifiasm.smk
Labels: bug, enhancement

#57 Feature: expose pbsv params in config
  config.yaml
  rules/cohort_pbsv.smk
  rules/sample_pbsv.smk
Labels: enhancement

#61 Feature: align assembly without chunking contigs
  rules/cohort_hifiasm.smk
  rules/envs/align_hifiasm.yaml
  rules/envs/bcftools.yaml
  rules/envs/htslib.yaml
  rules/envs/last.yaml
  rules/envs/samtools.yaml
  rules/sample_hifiasm.smk
Labels: enhancement

#78 add wildcards to trioeval log path
  rules/cohort_hifiasm.smk
Labels: bug
