Repository PacificBiosciences/pb-human-wgs-workflow-snakemake, pull requests merged in 2022-07, with the labels that each got.

#113 bugfix/leading_zero_sample_names
  process_cohort.local.sh
  process_cohort.lsf.sh
  process_cohort.sge.sh
  process_cohort.slurm.sh
  process_sample.local.sh
  process_sample.lsf.sh
  process_sample.sge.sh
  process_sample.slurm.sh
Labels: bug

#112 Bugfix/check for ml tag cleanup
  process_sample.smk
Labels: bug

#109 provide 4 threads to whatshap haplotag
  rules/sample_whatshap.smk
Labels: enhancement

#114 bugfixes
  process_cohort.local.sh
  process_cohort.lsf.sh
  process_cohort.sge.sh
  process_cohort.slurm.sh
  process_sample.local.sh
  process_sample.lsf.sh
  process_sample.sge.sh
  process_sample.slurm.sh
  process_sample.smk
  rules/sample_whatshap.smk
Labels: bug, enhancement
